services:
  neo4j:
    image: neo4j:5
    restart: always
    stop_signal: SIGTERM
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data/neo4j:/data
      - ./apoc.jar:/plugins/apoc.jar
    environment:
      - NEO4J_AUTH=none
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]

  kvrocks:
    image: apache/kvrocks
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/kvrocks:/var/lib/kvrocks
